name: Gource Action for all repositories
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      push:
        description: 'Run the workflow'
        required: false
        type: boolean
        default: true

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}
    steps:
      - name: Get Repositories Action
        id: get-repos
        uses: raven-actions/get-repos@v1
        with:
          format: json
          topics: 'run-gif-generator-chk'

  run-gource:
    name: Run Gource Action
    if: ${{ needs.get-repos.outputs.repos != '[]' }}
    runs-on: ubuntu-latest
    needs: [get-repos]
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.full_name }}
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1
        with:
          git_url: 'https://github.com/${{ matrix.repo.full_name }}'
          gource_title: '${{ matrix.repo.name }} gource'
          logo_url: 'https://github.com/git.png'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          avatars_auto_fetch: true
          gource_background_color: '0D1116'
          gource_overlay_background_color: '0D1116'
      - uses: actions/upload-artifact@v4
        with:
          name: gource-mp4-${{ github.run_number }}
          path: ./gource/gource.mp4

  convert-mp4-to-gif:
    name: Convert MP4 to GIF
    runs-on: ubuntu-latest
    needs: [run-gource]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/download-artifact@v4
        with:
          name: gource-mp4-${{ github.run_number }}
          path: ./gource
      - name: Setup FFmpeg
        run: |
          sudo apt update -y && \
          sudo apt install -y ffmpeg
      - name: Convert MP4 to GIF
        run: |
          ffmpeg -t 5 -i ./gource/gource.mp4 \
            -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
            -loop 0 ./gource/gource.gif
      - uses: actions/upload-artifact@v4
        with:
          name: gource-gif-${{ github.run_number }}
          path: ./gource/gource.gif

  commit-gource:
    name: Commit Gource
    if: ${{ needs.get-repos.outputs.repos != '[]' }}
    needs: [get-repos, run-gource, convert-mp4-to-gif]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Download Gource artifacts
        uses: actions/download-artifact@v4
        with:
          name: gource-gif-${{ github.run_number }}

      - name: Add GIF to README.md
        run: |
          mkdir -p assets
          mv gource.gif assets/gource.gif

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/gource.gif
          if [ -z "$(git status --porcelain)" ]; then
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Add new gource" -a
            echo "push=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
